### ISSUE TITLE
[CONTRIBUTION] A small guide on how to help out. 

### ISSUE THREAD

**Issue by nilq** [bukseng/kobe24#1]
Hello, I love working with programming languages and have spent a lot of time doing so. I have had a similar idea about a simple language for s long time, and would love to contribute once in a while. 

What do you need right now, and what does the language look like?

**Comment by bukseng** [comment]
Hi, here a sample video on how the language looks like as of now: https://youtu.be/-b_Met5aYKM  Aside from the todo in readme, I'm actually not sure but I think this repo is lacking compare to other repos. Like test, package or build stuffs. I'm not sure how to do those.

**Comment by bukseng** [comment]
Hi. I'm done with  making a Guide.md. As of now, it only shows how the language looks. I will later add some guide about things to be done.
